### ISSUE TITLE
How to obtain actual data?

### ISSUE THREAD

**Issue by zzz333za** [funkelab/linajea_experiments#1]
Hello, I want to obtain data related to the experiment, how can I get the  copy?

**Comment by abred** [comment]
Hello,

do you mean the raw/image data? Could you please specify which one you are interested in?

**Comment by zzz333za** [comment]
Yes, I am most interested in this 4.7T MOUSE dataset.Thank you very much for your reply.

**Comment by zzz333za** [comment]
Yes, I am most interested in this 4.7T MOUSE dataset.Thank you very much for your reply. @abred

**Comment by AkshitSharma1** [comment]
> Hello,
> 
> do you mean the raw/image data? Could you please specify which one you are interested in?

SIr, Even am interested in obtaining the dataset for the zebrafish. Please could you share it? @abred 
MY contact email for the same if required is akshitsharma2003@gmail.com

THanks a lot for your time

**Comment by abred** [comment]
Hi @zzz333za and @AkshitSharma1 ,
thank you for your interest.
As we did not create the data it is only available through their respective publications (see supplementary of our paper)

**Comment by cmalinmayor** [comment]
Update: mouse is now available on figshare here (with link to raw data on dropbox): https://doi.org/10.25378/janelia.24768798. Zebrafish will also be on figshare shortly.

**Comment by cmalinmayor** [comment]
All of the dataset access information is now on Figshare here: https://janelia.figshare.com/collections/Whole-embryo_lineage_reconstruction_with_linajea/7371652. Zebrafish specifically is here: https://janelia.figshare.com/articles/dataset/Zebrafish_data_for_whole-embryo_lineage_reconstruction_with_linajea/24968724.
Since this hopefully resolves the questions, I'll close the issue. Thanks for your interest!
